export const NICKNAMES = [
    'ECHO',     
    'SAGE',    
    'SKY',     
    'NORTH',    
    'WAVE',   
    'SPARK',   
    'DUSK',     
    'DAWN',    
    'MIST',     
    'SNOW',     
    'RAIN',        
    'ASH',      
    'STAR',       
    'CLOUD',    
    'LEAF',      
    'AURA',      
    'VALE', 
    'PINE',    
    'EAST',     
    'PEAK',      
    'FLARE',        
    'CLIFF',           
    'PRISM',        
    'SWIFT'      

export type Nickname = typeof NICKNAMES[number];
